"""UserTrail add no duplicate user id/trail id entries

Revision ID: 49d44a4f15ea
Revises: 61a5b4c8353a
Create Date: 2024-12-04 23:02:09.107176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d44a4f15ea'
down_revision = '61a5b4c8353a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trails', schema=None) as batch_op:
        batch_op.create_unique_constraint('no_duplicate_user_trail', ['user_id', 'trail_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trails', schema=None) as batch_op:
        batch_op.drop_constraint('no_duplicate_user_trail', type_='unique')

    # ### end Alembic commands ###
