"""UserTrail add is_saved column

Revision ID: 61a5b4c8353a
Revises: 4f8151c17aae
Create Date: 2024-12-04 00:08:55.324516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a5b4c8353a'
down_revision = '4f8151c17aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_saved', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trails', schema=None) as batch_op:
        batch_op.drop_column('is_saved')

    # ### end Alembic commands ###
